/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warsztat;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Karol
 */
public class Panel_Klienci extends javax.swing.JPanel {

    private Klient[] klienci;
    private Klient selKlient;
    private Auto[] auta;
    private Auto selAuto;
    private Panel_NoweAuto dialog1;
    private Panel_NowyKlient dialog2;
    public Panel_Klienci() {
        try {
            initComponents();
            DataControl.Connect("warsztat", "admin", "test");
            dialog1 = new Panel_NoweAuto(new javax.swing.JFrame(), true, this);
            dialog2 = new Panel_NowyKlient(new javax.swing.JFrame(),true,this);
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Klienci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void reset()
    {
        try {
            SWLista.clearSelection();
            DefaultListModel listModel = (DefaultListModel) SWLista.getModel();
            listModel.removeAllElements();
            klienci = DataControl.Klienci();
            for(int i = 0; i < klienci.length; i++)
            {
                listModel.addElement(klienci[i].getImie() + " " + klienci[i].getNazwisko());
            }
            resetText();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Klienci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void resetText()
    {
        if(selKlient == null)
        {
            SWImie.setText("");
            SWNazwisko.setText("");
            SWTele.setText("");
            SWMiejscowosc.setText("");
            SWUlica.setText("");
            SWMail.setText("");
            SWModel.setText("");
            SWMarka.setText("");
            SWReje.setText("");
            SWRok.setText("");
            SWAuta.clearSelection();
            DefaultListModel listModel = (DefaultListModel) SWAuta.getModel();
            listModel.removeAllElements();
        }
        else
        {
            try {
                SWImie.setText(selKlient.getImie());
                SWNazwisko.setText(selKlient.getNazwisko());
                SWTele.setText(selKlient.getTelnum());
                SWMiejscowosc.setText(selKlient.getMiejsc());
                SWUlica.setText(selKlient.getUlica());
                SWMail.setText(selKlient.getEmail());
                SWModel.setText("");
                SWMarka.setText("");
                SWReje.setText("");
                SWRok.setText("");
                SWAuta.clearSelection();
                DefaultListModel listModel = (DefaultListModel) SWAuta.getModel();
                listModel.removeAllElements();
                auta = DataControl.Auta(selKlient.getId());
                for(int i = 0; i < auta.length; i++)
                {
                    listModel.addElement(auta[i].getMarka() + " " + auta[i].getModel());
                }
            } catch (SQLException ex) {
                Logger.getLogger(Panel_Klienci.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SWLista = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SWImie = new javax.swing.JTextField();
        SWNazwisko = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SWMiejscowosc = new javax.swing.JTextField();
        SWUlica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SWMail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SWAuta = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        SWReje = new javax.swing.JTextField();
        SWRok = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        SWMarka = new javax.swing.JTextField();
        SWModel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        SWTele = new javax.swing.JFormattedTextField();

        SWLista.setModel(new DefaultListModel());
        SWLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SWListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(SWLista);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Nowy Klient");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jLabel1.setText("Imię");

        jLabel2.setText("Nazwisko");

        jLabel3.setText("Nr. Telefonu");

        jLabel6.setText("Miejscowość");

        jLabel7.setText("Ulica");

        jLabel8.setText("E-mail");

        jButton2.setText("Usuń");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        jButton3.setText("Zapisz");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });

        SWAuta.setModel(new DefaultListModel());
        SWAuta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SWAuta.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SWAutaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(SWAuta);

        jLabel9.setText("Auta");

        jLabel10.setText("Rejestracja");

        jLabel11.setText("Rok prod.");

        jButton4.setText("Zapisz Auto");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });

        jButton5.setText("Usuń Auto");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });

        jLabel12.setText("Marka");

        jLabel13.setText("Model");

        jButton6.setText("Dodaj Auto");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });

        try {
            SWTele.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SWImie)
                                    .addComponent(SWMiejscowosc)
                                    .addComponent(SWUlica)
                                    .addComponent(SWMail)
                                    .addComponent(SWNazwisko)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(SWTele)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SWModel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(SWMarka))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3)
                                    .addComponent(SWRok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(SWReje, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addContainerGap())
                    .addComponent(jSeparator2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(SWImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SWNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SWTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWReje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(SWMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SWModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SWListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SWListaValueChanged
        int n = SWLista.getSelectedIndex();
        if(n >= 0)
        {
           selKlient = klienci[n];
           dialog1.setId(selKlient.getId());
           resetText();
        }
        else
        {
           selKlient = null;
           resetText();
        }
    }//GEN-LAST:event_SWListaValueChanged

    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        if(selKlient != null)
        {
            dialog1.reset();
            dialog1.setVisible(true);
        }
    }//GEN-LAST:event_jButton6MouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        try {
            selKlient.setImie(SWImie.getText());
            selKlient.setNazwisko(SWNazwisko.getText());
            selKlient.setTelnum(SWTele.getText());
            selKlient.setMiejsc(SWMiejscowosc.getText());
            selKlient.setUlica(SWUlica.getText());
            selKlient.setEmail(SWMail.getText());
            DataControl.UpdKlient(selKlient);
            SWLista.clearSelection();
            reset();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        if(selAuto != null)
        {
            try {
                DataControl.DelCar(selAuto.getId());
                resetText();
            } catch (SQLException ex) {
                Logger.getLogger(Panel_Klienci.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5MouseReleased

    private void SWAutaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SWAutaValueChanged
        int n = SWAuta.getSelectedIndex();
        if(n >= 0)
        {
            selAuto = auta[n];
            SWMarka.setText(selAuto.getMarka());
            SWModel.setText(selAuto.getModel());
            SWReje.setText(selAuto.getRej());
            SWRok.setText(selAuto.getRok() + "");
        }
        else
        {
            selAuto = null;
            SWMarka.setText("");
            SWModel.setText("");
            SWReje.setText("");
            SWRok.setText("");
        }
    }//GEN-LAST:event_SWAutaValueChanged

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        if(selAuto != null)
        {
            try {
                selAuto.setMarka(SWMarka.getText());
                selAuto.setModel(SWModel.getText());
                selAuto.setRej(SWReje.getText());
                selAuto.setRok(Integer.parseInt(SWRok.getText()));
                DataControl.UpdAuto(selAuto);
                resetText();
            } catch (SQLException ex) {
                Logger.getLogger(Panel_Klienci.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        dialog2.setVisible(true);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        if(selKlient != null)
        {
            try {
                DataControl.DelKlient(selKlient.getId());
            } catch (SQLException ex) {
                Logger.getLogger(Panel_Klienci.class.getName()).log(Level.SEVERE, null, ex);
            }
            reset();
        }
    }//GEN-LAST:event_jButton2MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> SWAuta;
    private javax.swing.JTextField SWImie;
    private javax.swing.JList<String> SWLista;
    private javax.swing.JTextField SWMail;
    private javax.swing.JTextField SWMarka;
    private javax.swing.JTextField SWMiejscowosc;
    private javax.swing.JTextField SWModel;
    private javax.swing.JTextField SWNazwisko;
    private javax.swing.JTextField SWReje;
    private javax.swing.JTextField SWRok;
    private javax.swing.JFormattedTextField SWTele;
    private javax.swing.JTextField SWUlica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
