/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warsztat;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Karol
 */
public class Panel_Zgloszenia extends javax.swing.JPanel {

    Zgloszenie[] wolne;
    Zgloszenie[] aktywne;
    Zgloszenie[] zakonczone;
    Zgloszenie selZglo;
    int selectedList;
    Panel_NoweZgloszenie dialog;
    
    public Panel_Zgloszenia() {
        try {
            initComponents();
            DataControl.Connect("warsztat", "admin", "test");
            dialog = new Panel_NoweZgloszenie(new javax.swing.JFrame(), true,this);
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Zgloszenia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void reset()
    {
        selZglo = null;
        try {
            wolne = DataControl.wolneZgl();
            aktywne = DataControl.aktywneZgl();
            zakonczone = DataControl.zakonczoneZgl();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Zgloszenia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ListaWolne.clearSelection();
        ListaAktywne.clearSelection();
        ListaZakonczone.clearSelection();
        DefaultListModel listModel = (DefaultListModel) ListaWolne.getModel();
        listModel.removeAllElements();
        for(int i = 0; i < wolne.length; i++)
        {
            listModel.addElement(wolne[i].auto);
        }
        listModel = (DefaultListModel) ListaAktywne.getModel();
        listModel.removeAllElements();
        for(int i = 0; i < aktywne.length; i++)
        {
            listModel.addElement(aktywne[i].auto);
        }
        listModel = (DefaultListModel) ListaZakonczone.getModel();
        listModel.removeAllElements();
        for(int i = 0; i < zakonczone.length; i++)
        {
            listModel.addElement(zakonczone[i].auto);
        }
        resetText();
    }
    
    public void resetText()
    {
        if(selZglo != null)
        {
            SWOpis.setText(selZglo.opis);
            SWKlient.setText(selZglo.klient);
            SWTel1.setText(selZglo.telnum.substring(0, 3));
            SWTel2.setText(selZglo.telnum.substring(4, 7));
            SWTel3.setText(selZglo.telnum.substring(8, 11));
            SWAuto.setText(selZglo.auto);
            SWDataZgl.setText(selZglo.data1);
            SWDataPrz.setText(selZglo.data2);
            SWDataZwr.setText(selZglo.data3);
        }
        else
        {
            SWOpis.setText("");
            SWKlient.setText("");
            SWTel1.setText("");
            SWTel2.setText("");
            SWTel1.setText("");
            SWAuto.setText("");
            SWDataZgl.setText("");
            SWDataPrz.setText("");
            SWDataZwr.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaWolne = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaZakonczone = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListaAktywne = new javax.swing.JList<>();
        SWKlient = new javax.swing.JTextField();
        SWTel1 = new javax.swing.JTextField();
        SWTel2 = new javax.swing.JTextField();
        SWTel3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        SWAuto = new javax.swing.JTextField();
        SWDataZgl = new javax.swing.JTextField();
        SWDataPrz = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        SWDataZwr = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        SWOpis = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SWKoszt = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 360));
        setPreferredSize(new java.awt.Dimension(500, 360));

        jButton1.setText("Dodaj nowe zgłoszenie");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        ListaWolne.setModel(new DefaultListModel());
        ListaWolne.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaWolne.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaWolneFocusGained(evt);
            }
        });
        ListaWolne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaWolneMouseClicked(evt);
            }
        });
        ListaWolne.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaWolneValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaWolne);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ListaZakonczone.setModel(new DefaultListModel());
        ListaZakonczone.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaZakonczone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaZakonczoneFocusGained(evt);
            }
        });
        ListaZakonczone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaZakonczoneMouseClicked(evt);
            }
        });
        ListaZakonczone.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaZakonczoneValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(ListaZakonczone);

        ListaAktywne.setModel(new DefaultListModel());
        ListaAktywne.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaAktywne.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaAktywneFocusGained(evt);
            }
        });
        ListaAktywne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaAktywneMouseClicked(evt);
            }
        });
        ListaAktywne.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaAktywneValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(ListaAktywne);

        SWKlient.setEditable(false);
        SWKlient.setBackground(new java.awt.Color(255, 255, 255));
        SWKlient.setFocusable(false);

        SWTel1.setEditable(false);
        SWTel1.setBackground(new java.awt.Color(255, 255, 255));
        SWTel1.setFocusable(false);

        SWTel2.setEditable(false);
        SWTel2.setBackground(new java.awt.Color(255, 255, 255));
        SWTel2.setFocusable(false);

        SWTel3.setEditable(false);
        SWTel3.setBackground(new java.awt.Color(255, 255, 255));
        SWTel3.setFocusable(false);

        SWAuto.setEditable(false);
        SWAuto.setBackground(new java.awt.Color(255, 255, 255));
        SWAuto.setFocusable(false);

        SWDataZgl.setEditable(false);
        SWDataZgl.setBackground(new java.awt.Color(255, 255, 255));
        SWDataZgl.setFocusable(false);

        SWDataPrz.setEditable(false);
        SWDataPrz.setBackground(new java.awt.Color(255, 255, 255));
        SWDataPrz.setFocusable(false);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SWDataZwr.setEditable(false);
        SWDataZwr.setBackground(new java.awt.Color(255, 255, 255));
        SWDataZwr.setFocusable(false);

        SWOpis.setColumns(20);
        SWOpis.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        SWOpis.setRows(5);
        jScrollPane12.setViewportView(SWOpis);

        jButton2.setText("Zapisz");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        jButton3.setText("Usuń");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });

        jLabel1.setText("Wolne");

        jLabel2.setText("Aktualne");

        jLabel3.setText("Zakończone");

        jLabel4.setText("Koszt");

        SWKoszt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        SWKoszt.setFocusable(false);

        jLabel5.setText("Zgłaszający");

        jLabel6.setText("Nr.Tel");

        jLabel7.setText("Auto");

        jLabel8.setText("Data zgłoszenia");

        jLabel9.setText("Data zwrotu");

        jLabel10.setText("Data przyjęcia");

        jLabel11.setText("Opis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SWKlient))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SWDataZwr)
                            .addComponent(SWDataZgl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SWDataPrz, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SWKoszt))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SWAuto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SWTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SWTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SWTel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 69, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SWTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SWTel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SWTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SWAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(11, 11, 11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SWDataZgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SWDataPrz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SWDataZwr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SWKoszt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListaWolneValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaWolneValueChanged
        int i = ListaWolne.getSelectedIndex();
        if(i >= 0)
        {
            if(selectedList == 1)
            {
            ListaAktywne.clearSelection();
            ListaZakonczone.clearSelection();
            selZglo = wolne[i];
            }
        }
        else
            selZglo = null;
        resetText();
    }//GEN-LAST:event_ListaWolneValueChanged

    private void ListaZakonczoneValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaZakonczoneValueChanged
        int i = ListaZakonczone.getSelectedIndex();
        if(i >= 0)
        {
            if(selectedList == 3)
            {
                ListaAktywne.clearSelection();
                ListaWolne.clearSelection();
                selZglo = zakonczone[i];
            }
        }
        else
            selZglo = null;
        resetText();
    }//GEN-LAST:event_ListaZakonczoneValueChanged

    private void ListaAktywneValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaAktywneValueChanged
        int i = ListaAktywne.getSelectedIndex();
        if(i >= 0)
        {
            if(selectedList == 2)
            {
                ListaWolne.clearSelection();
                ListaZakonczone.clearSelection();
                selZglo = aktywne[i];
            }
        }
        else
            selZglo = null;
        resetText();
    }//GEN-LAST:event_ListaAktywneValueChanged

    private void ListaWolneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaWolneMouseClicked

    }//GEN-LAST:event_ListaWolneMouseClicked

    private void ListaAktywneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaAktywneMouseClicked

    }//GEN-LAST:event_ListaAktywneMouseClicked

    private void ListaZakonczoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaZakonczoneMouseClicked

    }//GEN-LAST:event_ListaZakonczoneMouseClicked

    private void ListaWolneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaWolneFocusGained
        selectedList = 1;
    }//GEN-LAST:event_ListaWolneFocusGained

    private void ListaAktywneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaAktywneFocusGained
        selectedList = 2;
    }//GEN-LAST:event_ListaAktywneFocusGained

    private void ListaZakonczoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaZakonczoneFocusGained
        selectedList = 3;
    }//GEN-LAST:event_ListaZakonczoneFocusGained

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        dialog.reset();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        if(selZglo != null)
            try {
                DataControl.UpdZgl(selZglo.id, SWOpis.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Zgloszenia.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset();
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        if(selZglo != null)
            try {
                DataControl.DelZglo(selZglo.id);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Zgloszenia.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset();
    }//GEN-LAST:event_jButton3MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaAktywne;
    private javax.swing.JList<String> ListaWolne;
    private javax.swing.JList<String> ListaZakonczone;
    private javax.swing.JTextField SWAuto;
    private javax.swing.JTextField SWDataPrz;
    private javax.swing.JTextField SWDataZgl;
    private javax.swing.JTextField SWDataZwr;
    private javax.swing.JTextField SWKlient;
    private javax.swing.JFormattedTextField SWKoszt;
    private javax.swing.JTextArea SWOpis;
    private javax.swing.JTextField SWTel1;
    private javax.swing.JTextField SWTel2;
    private javax.swing.JTextField SWTel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

}

